local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

yandex:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:yc, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:yc, :secret_access_key) %>
  region: ru-central1
  bucket: shishbbq
  endpoint: "https://storage.yandexcloud.net"
  force_path_style: true